"""End-to-end evidence run.

Exercises the full referral lifecycle against an in-process API and prints a
report that can be attached to the submission:

    python -m scripts.e2e_evidence
"""
import base64
import json
import os
import uuid

os.environ.setdefault("DATABASE_URL", "sqlite:///./e2e_evidence.db")
os.environ.setdefault("ENV", "test")
os.environ.setdefault("RATE_LIMIT_AUTH", "1000/60")
os.environ.setdefault("RATE_LIMIT_ATTRIBUTE", "1000/60")
os.environ.setdefault("RATE_LIMIT_AD_EVENT", "10000/60")
os.environ.setdefault("RATE_LIMIT_READ", "10000/60")

from fastapi.testclient import TestClient  # noqa: E402

from app.db.base import Base, engine  # noqa: E402
from app.main import app  # noqa: E402

PASS, FAIL = "PASS", "FAIL"
results = []


def check(name, condition, detail=""):
    results.append((PASS if condition else FAIL, name, detail))
    print(f"[{PASS if condition else FAIL}] {name} {detail}")


def device(device_id, browser="Chrome"):
    signals = {
        "platform": f"Linux-{device_id}", "screen": "1920x1080x24", "timezone": "Asia/Kolkata",
        "language": "en-IN", "hardware": f"8c-{device_id}", "canvasHint": f"hint-{device_id}",
    }
    raw = base64.urlsafe_b64encode(json.dumps(signals).encode()).decode().rstrip("=")
    return {"X-Device-Signals": raw, "User-Agent": f"Mozilla/5.0 ({browser})"}


def main():
    Base.metadata.drop_all(engine)
    Base.metadata.create_all(engine)

    with TestClient(app) as c:
        # 1. Referrer
        a = c.post("/api/auth/register", json={"email": "ayanalam@example.com", "password": "Password123!"},
                   headers=device("dev-a")).json()["data"]
        code = a["user"]["referralCode"]
        auth_a = {"Authorization": f"Bearer {a['accessToken']}"}
        check("Referral code generated by backend", code.startswith("VELOOP"), code)

        dash = c.get("/api/referrals/me", headers=auth_a).json()["data"]
        check("Referral link served by backend", dash["referralLink"].endswith(f"?ref={code}"),
              dash["referralLink"])

        # 2. Click != referral
        c.post("/api/referrals/click", json={"referralCode": code}, headers=device("dev-visitor"))
        check("Link click does not create a referral",
              c.get("/api/referrals/me", headers=auth_a).json()["data"]["totalReferrals"] == 0)

        # 3. Valid referral
        b = c.post("/api/auth/register",
                   json={"email": "rahulverma@example.com", "password": "Password123!", "referralCode": code},
                   headers=device("dev-b")).json()["data"]
        auth_b = {"Authorization": f"Bearer {b['accessToken']}"}
        check("Referral created as PENDING", b["referral"]["status"] == "PENDING")
        check("+20 XP credited on registration",
              c.get("/api/referrals/me", headers=auth_a).json()["data"]["totalXpEarned"] == 20)

        # 4. Immutability
        c2 = c.post("/api/auth/register", json={"email": "carol@example.com", "password": "Password123!"},
                    headers=device("dev-c")).json()["data"]
        again = c.post("/api/referrals/attribute", json={"referralCode": c2["user"]["referralCode"]},
                       headers={**auth_b, **device("dev-b")})
        check("Referral attribution immutable", again.json()["code"] == "REFERRAL_ALREADY_ASSIGNED")

        # 5. Ad milestones
        def watch(n):
            for _ in range(n):
                c.post("/api/ads/complete",
                       json={"provider": "veloop-sdk", "providerEventId": str(uuid.uuid4()), "watchedSeconds": 30},
                       headers={**auth_b, **device("dev-b")})

        watch(15)
        d = c.get("/api/referrals/me", headers=auth_a).json()["data"]
        check("15-ad milestone -> 5,000 SVE", d["totalSvesEarned"] == 5000, str(d["totalSvesEarned"]))

        watch(5)
        d = c.get("/api/referrals/me", headers=auth_a).json()["data"]
        check("20-ad milestone -> 2 Spins", d["totalSpinsEarned"] == 2)

        watch(10)
        d = c.get("/api/referrals/me", headers=auth_a).json()["data"]
        check("30-ad milestone -> 5,000 Tokens", d["totalTokensEarned"] == 5000)

        watch(5)
        d = c.get("/api/referrals/me", headers=auth_a).json()["data"]
        check("35-ad milestone -> 10 Gems", d["totalGemsEarned"] == 10)
        check("Referral becomes SUCCESSFUL", d["successfulReferrals"] == 1)

        # 6. Duplicate event / replay
        event = {"provider": "veloop-sdk", "providerEventId": "replay-evt-0001", "watchedSeconds": 30}
        c.post("/api/ads/complete", json=event, headers={**auth_b, **device("dev-b")})
        c.post("/api/ads/complete", json=event, headers={**auth_b, **device("dev-b")})
        after = c.get("/api/referrals/me", headers=auth_a).json()["data"]
        check("Duplicate events cannot duplicate rewards",
              after["totalSvesEarned"] == 5000 and after["totalGemsEarned"] == 10)

        # 7. Self-referral across another browser, same device
        self_ref = c.post("/api/auth/register",
                          json={"email": "ayan.second@example.com", "password": "Password123!",
                                "referralCode": code},
                          headers=device("dev-a", browser="Firefox"))
        body = self_ref.json()
        check("Self-referral detected across browsers", body.get("code") == "SELF_REFERRAL_DETECTED")
        check("Masked email returned", body.get("maskedEmail") == "ayan***lam@example.com",
              str(body.get("maskedEmail")))

        # 8. Spam handling / multi-account device
        c.post("/api/auth/register", json={"email": "m1@example.com", "password": "Password123!"},
               headers=device("dev-shared"))
        c.post("/api/auth/register", json={"email": "m2@example.com", "password": "Password123!"},
               headers=device("dev-shared"))
        spam_reg = c.post("/api/auth/register",
                          json={"email": "m3@example.com", "password": "Password123!", "referralCode": code},
                          headers=device("dev-shared")).json()["data"]
        d = c.get("/api/referrals/me", headers=auth_a).json()["data"]
        check("Multi-account device flagged", spam_reg["referral"]["status"] in ("FRAUD_REVIEW", "SPAM"),
              spam_reg["referral"]["status"])
        check("Spam count visible to user", d["spamReferrals"] >= 1, str(d["spamReferrals"]))
        check("Flagged referral earns nothing extra", d["totalXpEarned"] == 20)

        # 9. Authorization
        mallory = c.post("/api/auth/register", json={"email": "mallory@example.com", "password": "Password123!"},
                         headers=device("dev-m")).json()["data"]
        ref_id = c.get("/api/referrals", headers=auth_a).json()["data"]["items"][0]["id"]
        forbidden = c.get(f"/api/referrals/{ref_id}/progress",
                          headers={"Authorization": f"Bearer {mallory['accessToken']}"})
        check("Cannot read another user's referral", forbidden.status_code == 403)
        check("Unauthenticated access blocked", c.get("/api/referrals/me").status_code == 401)

        # 10. No sensitive data
        text = c.get("/api/referrals/me", headers=auth_a).text
        check("No raw email / fraud signals exposed",
              "rahulverma@example.com" not in text and "riskScore" not in text)

        # 11. Ledger reconciliation
        me = c.get("/api/auth/me", headers=auth_a).json()["data"]["balances"]
        check("Balances match ledger totals",
              me["sve"] == 5000 and me["gems"] == 10 and me["spins"] == 2 and me["xp"] == 20, str(me))

    failed = [r for r in results if r[0] == FAIL]
    print(f"\n{len(results) - len(failed)}/{len(results)} checks passed")
    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
