"""initial referral schema

Revision ID: 0001_initial
Revises: 
Create Date: 2026-09-16 06:05:15.059410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_initial'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('actor_user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=48), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('meta', sa.Text(), nullable=True),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_action_created', ['action', 'created_at'], unique=False)
        batch_op.create_index('ix_audit_entity', ['entity_type', 'entity_id'], unique=False)

    op.create_table('devices',
    sa.Column('device_hash', sa.String(length=64), nullable=False),
    sa.Column('first_ip_hash', sa.String(length=64), nullable=True),
    sa.Column('last_ip_hash', sa.String(length=64), nullable=True),
    sa.Column('user_agent_family', sa.String(length=64), nullable=True),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('blocked', sa.Boolean(), nullable=False),
    sa.Column('account_count', sa.Integer(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_device_hash'), ['device_hash'], unique=True)

    op.create_table('idempotency_records',
    sa.Column('scope', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('response_body', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope', 'user_id', 'key', name='uq_idempotency_request')
    )
    op.create_table('milestone_configs',
    sa.Column('milestone', sa.Integer(), nullable=False),
    sa.Column('reward_type', sa.String(length=16), nullable=False),
    sa.Column('reward_amount', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('subtitle', sa.String(length=64), nullable=True),
    sa.Column('condition_text', sa.String(length=160), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('milestone', 'reward_type', name='uq_milestone_reward_type')
    )
    op.create_table('referral_clicks',
    sa.Column('referral_code', sa.String(length=16), nullable=False),
    sa.Column('referrer_user_id', sa.String(length=36), nullable=True),
    sa.Column('device_hash', sa.String(length=64), nullable=True),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('user_agent_family', sa.String(length=64), nullable=True),
    sa.Column('converted_referral_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('referral_clicks', schema=None) as batch_op:
        batch_op.create_index('ix_clicks_code_created', ['referral_code', 'created_at'], unique=False)

    op.create_table('spam_referrals',
    sa.Column('referral_id', sa.String(length=36), nullable=True),
    sa.Column('referrer_user_id', sa.String(length=36), nullable=False),
    sa.Column('referred_user_id', sa.String(length=36), nullable=True),
    sa.Column('reason', sa.String(length=64), nullable=False),
    sa.Column('reason_detail', sa.Text(), nullable=True),
    sa.Column('risk_category', sa.String(length=32), nullable=False),
    sa.Column('device_hash', sa.String(length=64), nullable=True),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('spam_referrals', schema=None) as batch_op:
        batch_op.create_index('ix_spam_referrer', ['referrer_user_id'], unique=False)

    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('referral_code', sa.String(length=16), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('sve_balance', sa.Integer(), nullable=False),
    sa.Column('token_balance', sa.Integer(), nullable=False),
    sa.Column('gem_balance', sa.Integer(), nullable=False),
    sa.Column('spin_balance', sa.Integer(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_referral_code'), ['referral_code'], unique=True)

    op.create_table('ad_events',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_event_id', sa.String(length=128), nullable=False),
    sa.Column('ad_unit', sa.String(length=64), nullable=True),
    sa.Column('watched_seconds', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('eligible', sa.Boolean(), nullable=False),
    sa.Column('rejection_reason', sa.String(length=64), nullable=True),
    sa.Column('device_hash', sa.String(length=64), nullable=True),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_event_id', name='uq_ad_event_provider_id')
    )
    with op.batch_alter_table('ad_events', schema=None) as batch_op:
        batch_op.create_index('ix_ad_events_user_eligible', ['user_id', 'eligible'], unique=False)

    op.create_table('referrals',
    sa.Column('referrer_user_id', sa.String(length=36), nullable=False),
    sa.Column('referred_user_id', sa.String(length=36), nullable=True),
    sa.Column('referral_code', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attribution_source', sa.String(length=32), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(length=10), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['referred_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['referrer_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referred_user_id', name='uq_referral_referred_user')
    )
    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.create_index('ix_referrals_created_at', ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_referrals_referral_code'), ['referral_code'], unique=False)
        batch_op.create_index('ix_referrals_referrer_status', ['referrer_user_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_referrals_referrer_user_id'), ['referrer_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_referrals_status'), ['status'], unique=False)

    op.create_table('reward_transactions',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('referral_id', sa.String(length=36), nullable=True),
    sa.Column('reward_id', sa.String(length=36), nullable=True),
    sa.Column('reward_type', sa.String(length=16), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=120), nullable=False),
    sa.Column('milestone', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=190), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_txn_idempotency')
    )
    with op.batch_alter_table('reward_transactions', schema=None) as batch_op:
        batch_op.create_index('ix_txn_source', ['source'], unique=False)
        batch_op.create_index('ix_txn_user_type', ['user_id', 'reward_type'], unique=False)

    op.create_table('user_devices',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'device_id', name='uq_user_device')
    )
    with op.batch_alter_table('user_devices', schema=None) as batch_op:
        batch_op.create_index('ix_user_devices_device', ['device_id'], unique=False)

    op.create_table('referral_progress',
    sa.Column('referral_id', sa.String(length=36), nullable=False),
    sa.Column('referred_user_id', sa.String(length=36), nullable=False),
    sa.Column('eligible_ads_watched', sa.Integer(), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['referral_id'], ['referrals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referral_id', name='uq_progress_referral')
    )
    with op.batch_alter_table('referral_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_referral_progress_referred_user_id'), ['referred_user_id'], unique=False)

    op.create_table('referral_rewards',
    sa.Column('referral_id', sa.String(length=36), nullable=False),
    sa.Column('referrer_user_id', sa.String(length=36), nullable=False),
    sa.Column('reward_type', sa.String(length=16), nullable=False),
    sa.Column('reward_amount', sa.Integer(), nullable=False),
    sa.Column('milestone', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('credited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['referral_id'], ['referrals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referral_id', 'milestone', 'reward_type', name='uq_reward_once')
    )
    with op.batch_alter_table('referral_rewards', schema=None) as batch_op:
        batch_op.create_index('ix_rewards_referrer', ['referrer_user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('referral_rewards', schema=None) as batch_op:
        batch_op.drop_index('ix_rewards_referrer')

    op.drop_table('referral_rewards')
    with op.batch_alter_table('referral_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_referral_progress_referred_user_id'))

    op.drop_table('referral_progress')
    with op.batch_alter_table('user_devices', schema=None) as batch_op:
        batch_op.drop_index('ix_user_devices_device')

    op.drop_table('user_devices')
    with op.batch_alter_table('reward_transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_txn_user_type')
        batch_op.drop_index('ix_txn_source')

    op.drop_table('reward_transactions')
    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_referrals_status'))
        batch_op.drop_index(batch_op.f('ix_referrals_referrer_user_id'))
        batch_op.drop_index('ix_referrals_referrer_status')
        batch_op.drop_index(batch_op.f('ix_referrals_referral_code'))
        batch_op.drop_index('ix_referrals_created_at')

    op.drop_table('referrals')
    with op.batch_alter_table('ad_events', schema=None) as batch_op:
        batch_op.drop_index('ix_ad_events_user_eligible')

    op.drop_table('ad_events')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_referral_code'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('spam_referrals', schema=None) as batch_op:
        batch_op.drop_index('ix_spam_referrer')

    op.drop_table('spam_referrals')
    with op.batch_alter_table('referral_clicks', schema=None) as batch_op:
        batch_op.drop_index('ix_clicks_code_created')

    op.drop_table('referral_clicks')
    op.drop_table('milestone_configs')
    op.drop_table('idempotency_records')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_device_hash'))

    op.drop_table('devices')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_entity')
        batch_op.drop_index('ix_audit_action_created')

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
