"""Domain enums (stored as plain strings for easy migration/reporting)."""


class ReferralStatus:
    LINK_CLICKED = "LINK_CLICKED"
    PENDING = "PENDING"
    QUALIFYING = "QUALIFYING"
    SUCCESSFUL = "SUCCESSFUL"
    SPAM = "SPAM"
    REJECTED = "REJECTED"
    FRAUD_REVIEW = "FRAUD_REVIEW"

    ACTIVE = (PENDING, QUALIFYING, SUCCESSFUL)
    BLOCKED = (SPAM, REJECTED, FRAUD_REVIEW)


class RewardType:
    SVE = "SVE"
    XP = "XP"
    GEMS = "GEMS"
    TOKENS = "TOKENS"
    SPINS = "SPINS"

    ALL = (SVE, XP, GEMS, TOKENS, SPINS)


class RewardStatus:
    PENDING = "PENDING"
    CREDITED = "CREDITED"
    FAILED = "FAILED"
    BLOCKED = "BLOCKED"


class AdEventStatus:
    VERIFIED = "VERIFIED"
    REJECTED = "REJECTED"


class RiskLevel:
    LOW = "LOW"
    REVIEW = "REVIEW"
    HIGH = "HIGH"


class AuditAction:
    USER_REGISTERED = "USER_REGISTERED"
    REFERRAL_CLICK = "REFERRAL_CLICK"
    REFERRAL_CREATED = "REFERRAL_CREATED"
    REFERRAL_REJECTED = "REFERRAL_REJECTED"
    SELF_REFERRAL_DETECTED = "SELF_REFERRAL_DETECTED"
    REFERRAL_MARKED_SPAM = "REFERRAL_MARKED_SPAM"
    REFERRAL_COMPLETED = "REFERRAL_COMPLETED"
    MILESTONE_REACHED = "MILESTONE_REACHED"
    REWARD_CREDITED = "REWARD_CREDITED"
    REWARD_FAILED = "REWARD_FAILED"
    AD_EVENT_VERIFIED = "AD_EVENT_VERIFIED"
    AD_EVENT_REJECTED = "AD_EVENT_REJECTED"
    DEVICE_REGISTERED = "DEVICE_REGISTERED"
    ADMIN_STATUS_CHANGE = "ADMIN_STATUS_CHANGE"
